// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHwE8D4E2-fZWV7AyIVR_KY0DRBmlIwSg',
    appId: '1:464058622571:web:19b91f3b404a45b860472e',
    messagingSenderId: '464058622571',
    projectId: 'hoteldine',
    authDomain: 'hoteldine.firebaseapp.com',
    storageBucket: 'hoteldine.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-mmD1s6zhZEQ5Ek71sfz8kAl71Jfvi84',
    appId: '1:464058622571:android:7edc37685979769f60472e',
    messagingSenderId: '464058622571',
    projectId: 'hoteldine',
    storageBucket: 'hoteldine.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaqBdNrBWjtB7ifc-u3yXCkVqK1CiwtEQ',
    appId: '1:464058622571:ios:c50a47863ed622e560472e',
    messagingSenderId: '464058622571',
    projectId: 'hoteldine',
    storageBucket: 'hoteldine.firebasestorage.app',
    iosBundleId: 'com.example.hoteldineflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHwE8D4E2-fZWV7AyIVR_KY0DRBmlIwSg',
    appId: '1:464058622571:web:2c5bcffd7c3249a560472e',
    messagingSenderId: '464058622571',
    projectId: 'hoteldine',
    authDomain: 'hoteldine.firebaseapp.com',
    storageBucket: 'hoteldine.firebasestorage.app',
  );
}